### ISSUE TITLE
DeprecationWarning: Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by abhishek-gangwar** [interfaced/zombiebox-extension-dependency-injection#3]
After installing this package, "npx zombiebox run" command is giving the below error.

**[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

As a result app is not running. 

My node version v12.16.1 and npm version is 6.13.4

**Comment by l1bbcsg** [comment]
Hello! Thanks for your interest in ZombieBox.

This particular message is just Node's way of saying something went wrong, the actual error message is probably earlier in the log. Could you give us full output?
If there are no clearly useful messages, you could try increasing verbosity of output with `--log-level` parameter, for example: `--log-level debug`.

**Comment by abhishek-gangwar** [comment]
Below are the complete logs

```
node:93517) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'servicesAutodetect' of undefined
    at Builder.build (/Users/apple/Documents/2020/nodesmarttv/node_smart_tv_apps/node_modules/zombiebox-extension-dependency-injection/lib/builder.js:74:34)
    at Extension.generateCode (/Users/apple/Documents/2020/nodesmarttv/node_smart_tv_apps/node_modules/zombiebox-extension-dependency-injection/index.js:47:41)
    at /Users/apple/Documents/2020/nodesmarttv/node_smart_tv_apps/node_modules/zombiebox/lib/sources/source-provider-generated.js:167:76
    at Array.map (<anonymous>)
    at SourceProviderGenerated.generateExtensionsCode (/Users/apple/Documents/2020/nodesmarttv/node_smart_tv_apps/node_modules/zombiebox/lib/sources/source-provider-generated.js:166:38)
    at SourceProviderGenerated.generate (/Users/apple/Documents/2020/nodesmarttv/node_smart_tv_apps/node_modules/zombiebox/lib/sources/source-provider-generated.js:123:9)
    at async Promise.all (index 1)
(node:93517) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:93517) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
